version: '3.1'

services:

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: guillaume
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

  api:
    build: ./pm2
    environment:
      DB_HOST: db
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: guillaume
      DB_PORT: 5432
      JWT_SECRET: paul
    volumes:
      - .:/app
    ports:
      - 8081:4000
