version: '3.1'

services:

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

  api:
    build: ./pm2
    environment:
      DB_HOST: db
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: example
      DB_PORT: 5432
      JWT_SECRET: chamal
      NEWS_API_KEY: 07b6a91d43084b3ab23e2f99b5d67e37
      WEATHER_API_KEY: 7aeb3d7f3f5cf3e119bedccefb7b10e6
      PROM_URL: prom:9090
    volumes:
      - .:/app
    ports:
      - 8081:4000
